
RM := del

CXXFLAGS += --std=c++11
LIBFLAGS := -lpsapi


all: winrenice.exe

winrenice.exe: winrenice.cpp
	$(CXX) $(CXXFLAGS) -o $@ $< $(LIBFLAGS)

release: winrenice.exe
	strip --strip-unneeded $<

clean:
	-$(RM) *.o *.exe
